"""
Management command to create/update Chart Templates for the Revenue & Expenditure chapter.

Titles sourced DIRECTLY from the live page:
https://indiandistricts.in/statistics/maharashtra/ahilyanagar/revenue-expenditure/

Total: 64 charts across 9 sections.

Sections from TOC:
  1. GDDP and GDVA         (A-G, 7 charts) → RevenueGDDPGDVAN
  2. NDDP and NDVA         (A-G, 7 charts) → RevenueNDDPNDVAN
  3. Gram Panchayat        (A-G, 7 charts) → RevenueDSAGramPanchayatN
  4. Zilla Parishad        (A-J, 10 charts)→ RevenueDSAJillaParishadN
  5. Nagar Panchayat       (A-G, 7 charts) → RevenueDSANagarPanchayatN
  6. Municipal Councils    (A-G, 7 charts) → RevenueDSAMunicipalCounN
  7. Municipal Corporations(A-G, 7 charts) → RevenueDSAMunCorpN
  8. Banking               (A-E, 5 charts) → RevenueDSABankingN/DepositsN/LoansN
  9. Land Revenue          (A-B, 2 charts) → RevenueDSALandRevenueN
 10. Tax Revenue           (A-D, 4 charts) → RevenueDSATaxRevenueN / RevenueDSATaxRevenue
"""
from django.core.management.base import BaseCommand
from charthandler.models import ChartTemplate

DSA_SOURCE = 'District Statistical Abstract (DSA), Directorate of Economics and Statistics, Maharashtra'
GDDP_SOURCE = 'District Domestic Product Statistics, Directorate of Economics and Statistics, Maharashtra'


def opts(y_label, x_label='Year'):
    return {
        'scales': {
            'x': {'title': {'display': True, 'text': x_label}},
            'y': {'beginAtZero': True, 'title': {'display': True, 'text': y_label}},
        }
    }


class Command(BaseCommand):
    help = 'Creates Chart Templates for Revenue & Expenditure — titles from live site.'

    def handle(self, *args, **options):
        self.stdout.write('Creating Chart Templates for Revenue & Expenditure...\n')

        templates = [

            # ================================================================
            # SECTION 1: GDDP and GDVA  (7 charts)
            # src IDs: 47852–47858
            # ================================================================
            {
                'title': 'A. Gross District Domestic Product',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': ['gddp'],
                'dataset_config': [
                    {'label': 'GDDP (Rs. Lakh)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount(Rs.)'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': 'Gross District Domestic Product (GDDP) is the total monetary value of all goods and services produced within a district during a year.',
                'display_order': 1,
            },
            {
                'title': 'B. GDDP per Capita',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': ['per_capita_district_domestic_product'],
                'dataset_config': [
                    {'label': 'Amount(Rs.)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Per Capita GDDP (Rs.)'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': "GDDP per capita is the gross district domestic product divided by the district's population, showing the average economic output or income per person in that district.",
                'display_order': 2,
            },
            {
                'title': 'C. Gross District Value Added',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': ['gdva'],
                'dataset_config': [
                    {'label': 'GDVA (Rs. Lakh)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount(Rs.)'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': "Gross District Value Added (GDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production.",
                'display_order': 3,
            },
            {
                'title': 'D. Components of GDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': ['agriculture_allied_activities', 'industry', 'services_tertiary_sector'],
                'dataset_config': [
                    {'label': 'Agriculture & Allied Activities',   'backgroundColor': '#1a4570'},
                    {'label': 'Industry', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Services/ Tertiary Sector',  'backgroundColor': '#e46e53'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of GDVA'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': 'Gross District Value Added (GDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production.',
                'display_order': 4,
            },
            {
                'title': 'E. Components of Agriculture in GDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': ['crops', 'livestock', 'forestry_and_logging', 'fishing_and_aquaculture'],
                'dataset_config': [
                    {'label': 'Crops',                 'backgroundColor': '#1a4570'},
                    {'label': 'Livestock',             'backgroundColor': '#e9ba5d'},
                    {'label': 'Forestry & Logging',    'backgroundColor': '#e46e53'},
                    {'label': 'Fishing & Aquaculture', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of GDVA from Agriculture and Allied Activities'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': 'Components of Gross District Value Added (GDVA) show how much each sector contributes to the district\'s total economic output.',
                'display_order': 5,
            },
            {
                'title': 'F. Components of Industry in GDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': [
                    'manufacturing',
                    'mining_quarrying',
                    'construction',
                    'electricity_gas_water_supply_other_utility_services',
                ],
                'dataset_config': [
                    {'label': 'Manufacturing',          'backgroundColor': '#1a4570'},
                    {'label': 'Mining & Quarrying',     'backgroundColor': '#e9ba5d'},
                    {'label': 'Construction',           'backgroundColor': '#e46e53'},
                    {'label': 'Electricity, Gas, Water Supply & Other Utility Servicesy',  'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share GDVA from Industry'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': "Gross District Value Added (GDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production.",
                'display_order': 6,
            },
            {
                'title': 'G. Components of Services in GDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueGDDPGDVAN',
                'x_column': 'year',
                'y_columns': [
                    'real_estate_other_dwellings_and_professional_services',
                    'financial_services',
                    'trade_repair_and_hospitality',
                    'storage',
                    'public_administration_and_defence',
                    'transport_other_than_railways',
                    'railways',
                    'communication_and_broadcast_services',
                    'other_services',
                ],
                'dataset_config': [
                    {'label': 'Real Estate & Professional',      'backgroundColor': '#1a4570'},
                    {'label': 'Financial Services',              'backgroundColor': '#e9ba5d'},
                    {'label': 'Trade & Hospitality',             'backgroundColor': '#e46e53'},
                    {'label': 'Storage',                         'backgroundColor': '#af7c50'},
                    {'label': 'Public Admin & Defence',          'backgroundColor': '#a59f9c'},
                    {'label': 'Transport (Other)',               'backgroundColor': '#6cbde0'},
                    {'label': 'Railways',                        'backgroundColor': '#757595'},
                    {'label': 'Communication',                   'backgroundColor': '#478db8'},
                    {'label': 'Other Services',                  'backgroundColor': '#9c71c6'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of GDVA from Services'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': "Gross District Value Added (GDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production.",
                'display_order': 7,
            },

            # ================================================================
            # SECTION 2: NDDP and NDVA  (7 charts)
            # src IDs: 47859, 47918, 47861–47865
            # ================================================================
            {
                'title': 'A. Net District Domestic Product',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': ['nddp'],
                'dataset_config': [
                    {'label': 'NDDP (Rs. Lakh)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "Directorate of Economics and Statistics, Maharashtra",
                'additional_info': "NDDP (Net District Domestic Product) is the total value of goods and services produced within a district’s boundaries during a year, minus depreciation on capital asset",  
                'display_order': 8,
            },
            {
                'title': 'B. NDDP per Capita',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': ['per_capita_district_domestic_product'],
                'dataset_config': [
                    {'label': 'Per Capita NDDP (Rs.)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': "NDDP per capita is the Net District Domestic Product divided by the district's population, representing the average net income or economic output per person after accounting for depreciation.",
                'display_order': 9,
            },
            {
                'title': 'C. Net District Value Added',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': ['ndva'],
                'dataset_config': [
                    {'label': 'NDVA (Rs. Lakh)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs. Lakh)'),
                'description': 'Directorate of Economics and Statistics, Maharashtra',
                'additional_info': "Net District Value Added (NDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production and depreciation on fixed assets.",
                'display_order': 10,
            },
            {
                'title': 'D. Components of NDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': ['agriculture_allied_activities', 'industry', 'services_tertiary_sector'],
                'dataset_config': [
                    {'label': 'Agriculture & Allied Activities',   'backgroundColor': '#1a4570'},
                    {'label': 'Industry', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Services Tertiary Sector',  'backgroundColor': '#e46e53'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of NDVA'),
                'description': "Directorate of Economics and Statistics, Maharashtra",
                'additional_info': 'Net District Value Added (NDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production and depreciation on fixed assets.',
                'display_order': 11,
            },
            {
                'title': 'E. Components of Agriculture and Allied Activities in NDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': ['crops', 'livestock', 'forestry_and_logging', 'fishing_and_aquaculture'],
                'dataset_config': [
                    {'label': 'Crops',                 'backgroundColor': '#1a4570'},
                    {'label': 'Livestock',             'backgroundColor': '#e9ba5d'},
                    {'label': 'Forestry & Logging',    'backgroundColor': '#e46e53'},
                    {'label': 'Fishing & Aquaculture', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of NDVA from Agriculture and Allied Activities'),
                'description': "Directorate of Economics and Statistics, Maharashtra",
                'additional_info': "Net District Value Added (NDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production and depreciation on fixed assets.",
                'display_order': 12,
            },
            {
                'title': 'F. Components of Industry in NDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': [
                    'manufacturing',
                    'mining_quarrying',
                    'construction',
                    'electricity_gas_water_supply_other_utility_services',
                ],
                'dataset_config': [
                    {'label': 'Manufacturing',         'backgroundColor': '#1a4570'},
                    {'label': 'Mining & Quarrying',    'backgroundColor': '#e9ba5d'},
                    {'label': 'Construction',          'backgroundColor': '#e46e53'},
                    {'label': 'Electricity/Gas/Water', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of NDVA from Industry'),
                'description': "Directorate of Economics and Statistics, Maharashtra",
                'additional_info': "Net District Value Added (NDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production and depreciation on fixed assets.",
                'display_order': 13,
            },
            {
                'title': 'G. Components of Services in NDVA',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueNDDPNDVAN',
                'x_column': 'year',
                'y_columns': [
                    'real_estate_other_dwellings_and_professional_services',
                    'financial_services',
                    'trade_repair_and_hospitality',
                    'storage',
                    'public_administration_and_defence',
                    'transport_other_than_railways',
                    'railways',
                    'communication_and_broadcast_services',
                    'other_services',
                ],
                'dataset_config': [
                    {'label': 'Real Estate & Professional', 'backgroundColor': '#1a4570'},
                    {'label': 'Financial Services',         'backgroundColor': '#e9ba5d'},
                    {'label': 'Trade & Hospitality',        'backgroundColor': '#e46e53'},
                    {'label': 'Storage',                    'backgroundColor': '#af7c50'},
                    {'label': 'Public Admin & Defence',     'backgroundColor': '#a59f9c'},
                    {'label': 'Transport (Other)',          'backgroundColor': '#6cbde0'},
                    {'label': 'Railways',                   'backgroundColor': '#757595'},
                    {'label': 'Communication',              'backgroundColor': '#478db8'},
                    {'label': 'Other Services',             'backgroundColor': '#9c71c6'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of NDVA from Services'),
                'description': "Directorate of Economics and Statistics, Maharashtra",
                'additional_info': "Net District Value Added (NDVA) is the total value of goods and services produced within a district, minus the value of inputs used in production and depreciation on fixed assets.",
                'display_order': 14,
            },

            # ================================================================
            # SECTION 3: Gram Panchayat  (7 charts)
            # src IDs: 47880–47886
            # ================================================================
            {
                'title': 'A. Gram Panchayat Revenue and Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': ['revenue', 'expenditure'],
                'dataset_config': [
                    {'label': 'Revenue',     'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 15,
            },
            {
                'title': 'B. Composition of Revenue Sources for Gram Panchayats',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': ['land_and_property_taxes', 'other_taxes_and_charges', 'government_grants', 'contribution_donations_and_other_grants', 'other_sources'],
                'dataset_config': [
                    {'label': 'Land and Property Taxes',   'backgroundColor': '#1a4570'},
                    {'label': 'Other Taxes and Charges',        'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Grants', 'backgroundColor': '#e46e53'},
                    {'label': 'Contributions, Donations and Other Grants', 'backgroundColor': '#af7c50'},
                    {'label': 'Other Sources', 'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Revenue'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 16,
            },
            {
                'title': 'C. Composition of Expenditure for Gram Panchayats',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': [
                    'administration', 'health_and_hygiene', 'public_works',
                    'public_lighting', 'education', 'public_welfare', 'other_expenses',
                ],
                'dataset_config': [
                    {'label': 'Administration',   'backgroundColor': '#1a4570'},
                    {'label': 'Health & Hygiene', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Works',     'backgroundColor': '#e46e53'},
                    {'label': 'Public Lighting',  'backgroundColor': '#af7c50'},
                    {'label': 'Education',        'backgroundColor': '#a59f9c'},
                    {'label': 'Public Welfare',   'backgroundColor': '#6cbde0'},
                    {'label': 'Other Expenses',   'backgroundColor': '#757595'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Expenditure'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 17,
            },
            {
                'title': 'D. Gram Panchayat Tax Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': ['land_and_property_taxes', 'other_taxes_and_charges'],
                'dataset_config': [
                    {'label': 'Land and Property Taxes', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Other Taxes and Charges', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 18,
            },
            {
                'title': 'E. Gram Panchayat Non-Tax Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': ['government_grants', 'contribution_donations_and_other_grants', 'other_sources'],
                'dataset_config': [
                    {'label': 'Government Grants', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Contribution Donations and Other Grants', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Other Sources', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 19,
            },
            {
                'title': 'F. Gram Panchayat Developmental Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': ['education', 'health_and_hygiene', 'public_welfare', 'public_lighting', 'public_works'],
                'dataset_config': [ 
                    {'label': 'Education', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Health and Hygiene', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Welfare', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Public Lighting', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                    {'label': 'Public Works', 'borderColor': '#a59f9c', 'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 20,
            },
            {
                'title': 'G. Gram Panchayat Non-Developmental Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAGramPanchayatN',
                'x_column': 'year',
                'y_columns': ['administration', 'other_expenses'],
                'dataset_config': [
                    {'label': 'Administration', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Other Expenses', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 21,
            },

            # ================================================================
            # SECTION 4: Zilla Parishad  (10 charts A-J)
            # src IDs: 47887–47896
            # ================================================================
            {
                'title': 'A. Zilla Parishad Revenue and Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['revenue', 'expenditure'],
                'dataset_config': [
                    {'label': 'Revenue',     'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 22,
            },
            {
                'title': 'B. Composition of Revenue Sources for Zilla Parishads',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['self_generated', 'purposive_grants', 'establishment_grants','grants_for_plan_schemes','other_statutory_grants','for_agency_schemes','other_income'],
                'dataset_config': [
                    {'label': 'Self-Generated',   'backgroundColor': '#1a4570'},
                    {'label': 'Purposive Grants', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Establishment Grants',     'backgroundColor': '#e46e53'},
                    {'label': 'Grants for Plan Schemes',     'backgroundColor': '#af7c50'},
                    {'label': 'Other Statutory Grants',     'backgroundColor': '#a59f9c'},
                    {'label': 'For Agency Schemes',     'backgroundColor': '#6cbde0'},
                    {'label': 'Other Income',     'backgroundColor': '#757595'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Revenue'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 23,
            },
            {
                'title': 'C. Composition of Expenditure for Zilla Parishads',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': [
                    'general_administration', 'education', 'public_works','irrigation','agriculture',
                    'animal_husbandary', 'forests','public_health', 'social_welfare', 'other_expenses',
                ],
                'dataset_config': [
                    {'label': 'General Administration', 'backgroundColor': '#1a4570'},
                    {'label': 'Education',              'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Works',           'backgroundColor': '#e46e53'},
                    {'label': 'Irrigation',             'backgroundColor': '#af7c50'},
                    {'label': 'Animal Husbandry',       'backgroundColor': '#a59f9c'},
                    {'label': 'Forests',                'backgroundColor': '#6cbde0'},
                    {'label': 'Public Health',          'backgroundColor': '#757595'},
                    {'label': 'Social Welfare',         'backgroundColor': '#478db8'},
                    {'label': 'Agriculture',            'backgroundColor': '#9c71c6'},
                    {'label': 'Other Expenses',         'backgroundColor': '#7bbc9a'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Expenditure'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 24,
            },
            {
                'title': 'D. Revenue Earned: Revenue Account vs Capital Account',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'bar',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['revenue_income', 'capital_income'],
                'dataset_config': [
                    {'label': 'Revenue Income', 'backgroundColor': '#1a4570'},
                    {'label': 'Capital Income', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': 'Income in the revenue account refers to regular earnings such as taxes, fees, and interest that fund day-to-day government operations. Income in the capital account refers to receipts from non-recurring sources such as loans, sale of assets, or disinvestment used for creating or improving long-term assets.',
                'display_order': 25,
            },
            {
                'title': 'E. Zilla Parishad Self-Generated and Other Sources of Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['self_generated', 'other_income'],
                'dataset_config': [
                    {'label': 'Self-Generated ', 'backgroundColor': '#1a4570'},
                    {'label': 'Other Income',   'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': 'The total revenue of Zilla Parishads comprises self-generated income, revenue from grants, and other sources of income.',
                'display_order': 26,
            },
            {
                'title': 'F. Zilla Parishad Revenue from Grants',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['purposive_grants', 'establishment_grants','grants_for_plan_schemes','other_statutory_grants','for_agency_schemes'],
                'dataset_config': [
                    {'label': 'Purposive Grants', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Establishment Grants', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Grants for Plan Schemes', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Other Statutory Grants', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                    {'label': 'For Agency Schemes', 'borderColor': '#a59f9c', 'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 27,
            },
            {
                'title': 'G. Zilla Parishad Developmental Expenditure: Social Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['education','public_health','social_welfare'],
                'dataset_config': [
                    {'label': 'Education', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Public Health', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Social Welfare', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 28,
            },
            {
                'title': 'H. Zilla Parishad Developmental Expenditure: Economic Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['public_works','irrigation','agriculture','animal_husbandry','forests'],
                'dataset_config': [
                    {'label': 'Public Works', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Irrigation', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Agriculture', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Animal Husbandry', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                    {'label': 'Forests', 'borderColor': '#a59f9c', 'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 29,
            },
            {
                'title': 'I. Zilla Parishad Non-Developmental Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['general_administration','other_expenses'],
                'dataset_config': [
                    {'label': 'General Administration', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Other Expenses', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 30,
            },
            {
                'title': 'J. Zilla Parishad Opening Balance',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAJillaParishadN',
                'x_column': 'year',
                'y_columns': ['opening_balance'],
                'dataset_config': [
                    {'label': 'Opening Balance', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': 'Opening balance refers to the amount of funds available at the start of a financial year, carried forward from the previous year’s closing balance.',
                'display_order': 31,
            },

            # ================================================================
            # SECTION 5: Nagar Panchayat  (7 charts A-G)
            # src IDs: 47897–47903
            # ================================================================
            {
                'title': 'A. Nagar Panchayat Revenue and Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': ['revenue', 'expenditure'],
                'dataset_config': [
                    {'label': 'Revenue',     'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 32,
            },
            {
                'title': 'B. Composition of Revenue Sources for Nagar Panchayats',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': ['receipts_and_loans', 'from_commercial_activities', 'government_subsidies', 'rents_and_taxes','other_sources'],
                'dataset_config': [
                    {'label': 'Reciepts and Loans',         'backgroundColor': '#1a4570'},
                    {'label': 'From Commercial Activities', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Subsidies',  'backgroundColor': '#e46e53'},
                    {'label': 'Rents and Taxes',         'backgroundColor': '#af7c50'},
                    {'label': 'Other Sources',         'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Revenue'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 33,
            },
            {
                'title': 'C. Composition of Expenditure for Nagar Panchayats',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': [
                    'administration_establishment', 'administration_others','construction', 'drainage_and_sewage',
                    'education', 'expenditure_on_weak_components', 'public_health','public_lighting','public_security','special_expenses_and_loans','tax_recovery', 'transportation', 'water_supply','others',
                ],
                'dataset_config': [
                    {'label': 'Administration (Establishment)',    'backgroundColor': '#1a4570'},
                    {'label': 'Administration (Others)',         'backgroundColor': '#e9ba5d'},
                    {'label': 'Construction',     'backgroundColor': '#e46e53'},
                    {'label': 'Drainage & Sewage',      'backgroundColor': '#af7c50'},
                    {'label': 'Education',      'backgroundColor': '#a59f9c'},
                    {'label': 'Expenditure on Weak Components', 'backgroundColor': '#6cbde0'},
                    {'label': 'Public Health',   'backgroundColor': '#757595'},
                    {'label': 'Public Lighting',   'backgroundColor': '#478db8'},
                    {'label': 'Public Security',    'backgroundColor': '#9c71c6'},
                    {'label': 'Special Expenses and Loans',            'backgroundColor': '#7bbc9a'},
                    {'label': 'Tax Recovery',            'backgroundColor': '#789ec4'},
                    {'label': 'Transportation',            'backgroundColor': '#e8d2a6'},
                    {'label': 'Water Supply',            'backgroundColor': '#a66354'},
                    {'label': 'Others',            'backgroundColor': '#463582'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Expenditure'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 34,
            },
            {
                'title': 'D. Nagar Panchayat Sources of Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': ['receipts_and_loans', 'from_commercial_activities', 'government_subsidies', 'rents_and_taxes','other_sources'],
                'dataset_config': [
                    {'label': 'Receipts and Loans',         'backgroundColor': '#1a4570'},
                    {'label': 'From Commercial Activities', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Subsidies',  'backgroundColor': '#e46e53'},
                    {'label': 'Rents and Taxes',         'backgroundColor': '#af7c50'},
                    {'label': 'Receipts and Loans',         'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 35,
            },
            {
                'title': 'E. Nagar Panchayat Developmental Expenditure: Social Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': ['education','expenditure_on_weak_components','public_health','water_supply'],
                'dataset_config': [
                    {'label': 'Education', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure on Weak Components', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Health', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Water Supply', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 36,
            },
            {
                'title': 'F. Nagar Panchayat Developmental Expenditure: Economic Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': ['construction','drainage_and_sewage','public_lighting','transportation'],
                'dataset_config': [
                    {'label': 'Construction', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Drainage and Sewage', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Lighting', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Transportation', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 37,
            },
            {
                'title': 'G. Nagar Panchayat Non-Developmental Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSANagarPanchayatN',
                'x_column': 'year',
                'y_columns': ['administration_establishment','administration_others','others'],
                'dataset_config': [
                    {'label': 'Administration (Establishment)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Administration (Others)', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Other', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 38,
            },

            # ================================================================
            # SECTION 6: Municipal Councils  (7 charts A-G)
            # src IDs: 47904–47910
            # ================================================================
            {
                'title': 'A. Municipal Council Revenue and Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': ['revenue', 'expenditure'],
                'dataset_config': [
                    {'label': 'Revenue (Rs.)',     'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure (Rs.)', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs. Lakh)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 39,
            },
            {
                'title': 'B. Composition of Revenue Sources for Municipal Councils',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': ['receipts_and_loans', 'from_commercial_activities', 'government_subsidies','rents_and_taxes', 'other_sources'],
                'dataset_config': [
                    {'label': 'Receipts and Loans',         'backgroundColor': '#1a4570'},
                    {'label': 'FromCommercial Activities', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Subsidies',  'backgroundColor': '#e46e53'},
                    {'label': 'Rents and Taxes',         'backgroundColor': '#af7c50'},
                    {'label': 'Other Sources',         'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Revenue'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 40,
            },
            {
                'title': 'C. Composition of Expenditure for Municipal Councils',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': [
                     'administration_establishment', 'administration_others','construction', 'drainage_and_sewage',
                    'education', 'expenditure_on_weak_sectors', 'public_health','public_lighting','public_security','special_expenses_and_loans','tax_recovery', 'transportation', 'water_supply','others',
               ],
                'dataset_config': [
                    {'label': 'Administration (Establishment)',    'backgroundColor': '#1a4570'},
                    {'label': 'Administration (Others)',         'backgroundColor': '#e9ba5d'},
                    {'label': 'Construction',     'backgroundColor': '#e46e53'},
                    {'label': 'Drainage & Sewage',      'backgroundColor': '#af7c50'},
                    {'label': 'Education',      'backgroundColor': '#a59f9c'},
                    {'label': 'Expenditure on Weak Components', 'backgroundColor': '#6cbde0'},
                    {'label': 'Public Health',   'backgroundColor': '#757595'},
                    {'label': 'Public Lighting',   'backgroundColor': '#478db8'},
                    {'label': 'Public Security',    'backgroundColor': '#9c71c6'},
                    {'label': 'Special Expenses and Loans',            'backgroundColor': '#7bbc9a'},
                    {'label': 'Tax Recovery',            'backgroundColor': '#789ec4'},
                    {'label': 'Transportation',            'backgroundColor': '#e8d2a6'},
                    {'label': 'Water Supply',            'backgroundColor': '#a66354'},
                    {'label': 'Others',            'backgroundColor': '#463582'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Expenditure'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 41,
            },
            {
                'title': 'D. Municipal Council Sources of Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': [ 'receipts_and_loans', 'from_commercial_activities', 'government_subsidies','rents_and_taxes', 'other_sources'],
                'dataset_config': [
                    {'label': 'Receipts and Loans',         'backgroundColor': '#1a4570'},
                    {'label': 'Commercial Activities', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Subsidies',  'backgroundColor': '#e46e53'},
                    {'label': 'Rents & Taxes',         'backgroundColor': '#af7c50'},
                    {'label': 'Other Sources',         'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 42,
            },
            {
                'title': 'E. Municipal Council Developmental Expenditure: Social Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': ['education','expenditure_on_weak_sectors','public_health','water_supply'],
                'dataset_config': [
                    {'label': 'Education', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure on Weak Components', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Health', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Water Supply', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 43,
            },
            {
                'title': 'F. Municipal Council Developmental Expenditure: Economic Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': ['construction','drainage_and_sewage','public_lighting','transportation'],
                'dataset_config': [
                    {'label': 'Construction', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Drainage and Sewage', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Lighting', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Transportation', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 44,
            },
            {
                'title': 'G. Municipal Councils Non-Developmental Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunicipalCounN',
                'x_column': 'year',
                'y_columns': ['administration_establishment','administration_others','special_expenses_and_loans','public_security','tax_recovery','others'],
                'dataset_config': [
                    {'label': 'Administration (Establishment)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Administration (Others)', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Special Expenses and Loans', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Public Security', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                    {'label': 'Tax Recovery', 'borderColor': '#a59f9c', 'backgroundColor': '#a59f9c'},
                    {'label': 'Others', 'borderColor': '#6cbde0', 'backgroundColor': '#6cbde0'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 45,
            },

            # ================================================================
            # SECTION 7: Municipal Corporations  (7 charts A-G)
            # src IDs: 47911–47917
            # ================================================================
            {
                'title': 'A. Municipal Corporation Revenue and Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': ['revenue', 'expenditure'],
                'dataset_config': [
                    {'label': 'Revenue (Rs.)',     'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure (Rs.)', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 46,
            },
            {
                'title': 'B. Composition of Revenue Sources for Municipal Corporations',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': ['receipts_and_loans','from_commercial_activities', 'government_subsidy','rents_and_taxes', 'other_sources'],
                'dataset_config': [
                    {'label': 'Receipts and Loans',    'backgroundColor': '#1a4570'},
                    {'label': 'Commercial Activities', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Subsidy',    'backgroundColor': '#e46e53'},
                    {'label': 'Rents & Taxes',         'backgroundColor': '#af7c50'},
                    {'label': 'Other Sources',         'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Revenue'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 47,
            },
            {
                'title': 'C. Composition of Expenditure for Municipal Corporations',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'percentStackedBar',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': [
                    'administration_establishment', 'administration_others', 'construction',
                    'drainage_and_sewage', 'education', 'expenditure_on_weak_components',
                    'public_health','public_lighting', 'public_security', 'special_expenses_and_loans',
                    'tax_recovery', 'transportation', 'water_supply','others'
                ],
                'dataset_config': [
                    {'label': 'Administration (Establishment)', 'backgroundColor': '#1a4570'},
                    {'label': 'Administration (Others)',        'backgroundColor': '#e9ba5d'},
                    {'label': 'Construction',     'backgroundColor': '#e46e53'},
                    {'label': 'Drainage & Sewage',      'backgroundColor': '#af7c50'},
                    {'label': 'Education',      'backgroundColor': '#a59f9c'},
                    {'label': 'Expenditure on Weak Components', 'backgroundColor': '#6cbde0'},
                    {'label': 'Public Health',   'backgroundColor': '#757595'},
                    {'label': 'Public Lighting',    'backgroundColor': '#478db8'},
                    {'label': 'Public Security',    'backgroundColor': '#9c71c6'},
                    {'label': 'Special Expenses and Loans',    'backgroundColor': '#7bbc9a'},
                    {'label': 'Tax Recovery',    'backgroundColor': '#789ec4'},
                    {'label': 'Transportation',    'backgroundColor': '#e8d2a6'},
                    {'label': 'Water Supply',    'backgroundColor': '#a66354'},
                    {'label': 'Others',            'backgroundColor': '#463582'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Share of Expenditure'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 48,
            },
            {
                'title': 'D. Municipal Corporation Sources of Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': ['receipts_and_loans','from_commercial_activities', 'government_subsidy', 'rents_and_taxes', 'other_sources'],
                'dataset_config': [
                    {'label': 'Receipts and Loans', 'backgroundColor': '#1a4570'},
                    {'label': 'Commercial Activities', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Government Subsidy',    'backgroundColor': '#e46e53'},
                    {'label': 'Rents & Taxes',         'backgroundColor': '#af7c50'},
                    {'label': 'Other Sources',         'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 49,
            },
            {
                'title': 'E. Municipal Corporation Developmental Expenditure: Social Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': ['education','expenditure_on_weak_components','public_health','water_supply'],
                'dataset_config': [
                    {'label': 'Education', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Expenditure on Weak Components', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Health', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Water Supply', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 50,
            },
            {
                'title': 'F. Municipal Corporation Developmental Expenditure: Economic Services',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': ['construction','drainage_and_sewage','public_lighting','public_security', 'transportation'],
                'dataset_config': [
                    {'label': 'Construction', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Drainage and Sewage', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Public Lighting', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Public Security', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                    {'label': 'Transportation', 'borderColor': '#a59f9c', 'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 51,
            },
            {
                'title': 'G. Municipal Corporation Non-Developmental Expenditure',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSAMunCorpN',
                'x_column': 'year',
                'y_columns': ['administration_establishment','administration_others','special_expenses_and_loans', 'public_security','tax_recovery', 'others'],
                'dataset_config': [
                    {'label': 'Administration (Establishment)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                    {'label': 'Administration (Others)', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                    {'label': 'Special Expenses and Loans', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                    {'label': 'Tax Recovery', 'borderColor': '#af7c50', 'backgroundColor': '#af7c50'},
                    {'label': 'Others', 'borderColor': '#a59f9c', 'backgroundColor': '#a59f9c'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 52,
            },

            # ================================================================
            # SECTION 8: Banking  (5 charts A-E)
            # src IDs: 47920–47924
            # ================================================================
            {
                'title': 'A. Amount Deposited in Banks',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSADepositsN',
                'x_column': 'year',
                'y_columns': ['deposits'],
                'dataset_config': [
                    {'label': 'Deposits', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': '',
                'show_filters': True,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 53,
            },
            {
                'title': 'B. Loans Taken from Banks',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSALoansN',
                'x_column': 'year',
                'y_columns': ['total_loans'],
                'dataset_config': [
                    {'label': 'Total Loans', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': '',
                'show_filters': True,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 54,
            },
            {
                'title': 'C. Type of Loans Taken',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSALoansN',
                'x_column': 'year',
                'y_columns': ['agriculture_loans', 'non_agriculture_loans'],
                'dataset_config': [
                    {'label': 'Agriculture Loans',     'backgroundColor': '#1a4570'},
                    {'label': 'Non-Agriculture Loans', 'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': '',
                'show_filters': True,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 55,
            },
            {
                'title': 'D. Classified Banks and their Branch Offices',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSABanking2',
                'x_column': 'year',
                'y_columns': ['number'],
                'dataset_config': [
                    {'label': 'Classified Banks',   'backgroundColor': '#1a4570'},
                    {'label': 'Branch Offices',     'backgroundColor': '#e9ba5d'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': 'select_bank',
                'show_filters': True,
                'chart_options': opts('Number'),
                'description': "District Statistical Abstracts",
                'additional_info': 'A classified bank is a bank categorized under a specific group, such as commercial, cooperative, or regional rural banks, based on its functions and regulations.',
                'display_order': 56,
            },
            {
                'title': 'E. Towns and Cities where Banks have Offices',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSABankingN',
                'x_column': 'year',
                'y_columns': ['towns_and_cities_where_banks_have_offices'],
                'dataset_config': [
                    {'label': 'Towns/Cities where Banks have Offices', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': '',
                'show_filters': True,
                'chart_options': opts('Number'),
                'description': 'District Statistical Abstracts',
                'additional_info': '',
                'display_order': 57,
            },

            # ================================================================
            # SECTION 9: Land Revenue  (2 charts A-B)
            # src IDs: 47926–47927
            # ================================================================
            {
                'title': 'A. Aggregate Current Demand for Land Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSALandRevenueN',
                'x_column': 'year',
                'y_columns': ['aggregate_current_demand'],
                'dataset_config': [
                    {'label': 'Aggregate Current Demand', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': '',
                'show_filters': True,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': 'Aggregate current demand for land revenue is the total amount of land revenue due for payment in the current period.',
                'display_order': 58,
            },
            {
                'title': 'B. Arrears of Land Revenue',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSALandRevenueN',
                'x_column': 'year',
                'y_columns': ['arrears'],
                'dataset_config': [
                    {'label': 'Arrears', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': 'taluka',
                'filter2_column': '',
                'show_filters': True,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': 'Arrears of land revenue are unpaid amounts of land revenue that remain due from previous periods.',
                'display_order': 59,
            },

            # ================================================================
            # SECTION 10: Tax Revenue  (4 charts A-D)
            # src IDs: 47929–47932
            # ================================================================
            {
                'title': 'A. Value Added Tax (VAT)',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSATaxRevenueN',
                'x_column': 'year',
                'y_columns': ['value_added_tax_vat'],
                'dataset_config': [
                    {'label': 'Value Added Tax (VAT)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 60,
            },
            {
                'title': 'B. Stamp and Registration Fees',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSATaxRevenueN',
                'x_column': 'year',
                'y_columns': ['stamp_and_registration_fee'],
                'dataset_config': [
                    {'label': 'Stamp & Registration Fees', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 61,
            },
            {
                'title': 'C. State Excise Duty',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSATaxRevenueN',
                'x_column': 'year',
                'y_columns': ['state_excise_duty'],
                'dataset_config': [
                    {'label': 'State Excise Duty', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.)'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 62,
            },
            {
                'title': 'D. Land Tax',
                'chapter_type': 'revenue-expenditure',
                'chart_type': 'line',
                'data_source_table': 'RevenueDSATaxRevenueN',
                'x_column': 'year',
                'y_columns': ['land_tax'],
                'dataset_config': [
                    {'label': 'Land Tax', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                ],
                'main_filter_column': 'district',
                'filter1_column': '',
                'filter2_column': '',
                'show_filters': False,
                'chart_options': opts('Amount (Rs.'),
                'description': "District Statistical Abstracts",
                'additional_info': '',
                'display_order': 63,
            },
        ]

        # ------------------------------------------------------------------
        # Create or update each template (never delete — DynamicChartBlock
        # has a PROTECTED FK so deleting ChartTemplate rows would fail)
        # ------------------------------------------------------------------
        count_new = 0
        count_updated = 0

        for config in templates:
            obj, created = ChartTemplate.objects.update_or_create(
                title=config['title'],
                chapter_type=config['chapter_type'],
                defaults=config,
            )
            if created:
                count_new += 1
                self.stdout.write(f'  [NEW] {obj.title}')
            else:
                count_updated += 1
                self.stdout.write(f'  [UPD] {obj.title}')

        self.stdout.write(self.style.SUCCESS(
            f'\nDone! {len(templates)} templates processed. ({count_new} new, {count_updated} updated)'
        ))
