"""Management command to create the default Chart Templates for Health."""
from django.core.management.base import BaseCommand
from charthandler.models import ChartTemplate

def build_chart_options(y_axis_title, is_percent=False, disable_all_filter1=False, disable_all_filter2=False):
    options = {
        'scales': {
            'x': {'title': {'display': True, 'text': 'Year'}},
            'y': {'beginAtZero': True, 'title': {'display': True, 'text': y_axis_title}}
        }
    }
    if is_percent:
      #   options['scales']['y']['max'] = 100
        options['is_percentage_format'] = True
    if disable_all_filter1:
        options['disable_all_filter1'] = True
    if disable_all_filter2:
        options['disable_all_filter2'] = True
    return options

   

# # To disable "All" for filter 1 (e.g., Facility), but keep it for filter 2 (e.g., Taluka)
# 'chart_options': build_chart_options('Number', False, disable_all_filter1=True)
# # To disable "All" for filter 2 only
# 'chart_options': build_chart_options('Number', False, disable_all_filter2=True)
# # To disable "All" for BOTH filters
# 'chart_options': build_chart_options('Number', False, disable_all_filter1=True, disable_all_filter2=True)

class Command(BaseCommand):
    help = 'Creates/Updates Chart Templates for Health.'

    def handle(self, *args, **options):
        self.stdout.write('Creating Chart Templates for Health...')
        templates = [
            {
            'title': 'A. Public and Govt-Aided Medical Facilities',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAPublicHospitals2',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_facility',
            'filter2_column': 'taluka',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False, disable_all_filter1=True),
            'description': ' District Statistical Abstracts',
            'additional_info': '',
            'display_order': 1,
            },
            {
            'title': 'B. Private Healthcare Facilities',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAPrivateHealth2',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_facility',
            'filter2_column': 'taluka',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter1=True),
            'description': ' District Statistical Abstracts',
            'additional_info': '',
            'display_order': 2,
            },
            {
            'title': 'C. Approved vs Working Anganwadi',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAAnganwadis',
            'x_column': 'year',
            'y_columns': ['approved_anganwadis', 'working_anganwadis'],
            'dataset_config': [
                {'label': 'Approved Anganwadis', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Working Anganwadis', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 3,
            },
            {
            'title': 'D. Anganwadi Building Types',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAAnganwadis',
            'x_column': 'year',
            'y_columns': ['self_owned_buildings', 'rental_buildings', 'without_regular_building', 'anganwadis_with_toilets'],
            'dataset_config': [
                {'label': 'Self-Owned Buildings', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Rental Buildings', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Without Regular Building', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Anganwadis with Toilets', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 4,
            },
            {
            'title': 'E. Anganwadi Workers',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAAnganwadis',
            'x_column': 'year',
            'y_columns': ['anganwadi_workers'],
            'dataset_config': [
                {'label': 'Anganwadi Workers', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 5,
            },
            {
            'title': 'F. Patients in In-Patients Department',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISPatients',
            'x_column': 'year',
            'y_columns': ['inpatients'],
            'dataset_config': [
                {'label': 'Inpatients', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 6,
            },
            {
            'title': 'G. Patients in Outpatients Department',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISPatients',
            'x_column': 'year',
            'y_columns': ['outpatients'],
            'dataset_config': [
                {'label': 'Outpatients', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 7,
            },
            {
            'title': 'H. Outpatient-to-Inpatient Ratio',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISPatients',
            'x_column': 'year',
            'y_columns': ['outpatients_to_inpatients'],
            'dataset_config': [
                {'label': 'Outpatients to Inpatients', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('No. of Out-Patients(per In-Patient)', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 8,
            },
            {
            'title': 'I. Patients Treated in Public Facilities',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAPublicOutPatients',
            'x_column': 'year',
            'y_columns': ['male', 'female', 'children'],
            'dataset_config': [
                {'label': 'Male', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Female', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Children', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'type',
            'filter2_column': 'taluka',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 9,
            },
            {
            'title': 'J. Operations Conducted',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISPatients',
            'x_column': 'year',
            'y_columns': ['major_operations', 'minor_operations'],
            'dataset_config': [
                {'label': 'Major Operations', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Minor Operations', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 10,
            },
            {
            'title': 'K. Hysterectomies Performed',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISPatients',
            'x_column': 'year',
            'y_columns': ['hysterectomies_performed'],
            'dataset_config': [
                {'label': 'Hysterectomies Performed', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 11,
            },
            {
            'title': 'L. Share of Households with Access to Health Amenities',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSFacilities',
            'x_column': 'year',
            'y_columns': ['iodized_salt', 'clean_fuel_for_cooking', 'improved_drinking_water_source', 'improved_sanitation_facility', 'health_insurance_or_financing_scheme'],
            'dataset_config': [
                {'label': 'Iodized Salt', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Clean Fuel for Cooking', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Improved Drinking Water Source', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Improved Sanitation Facility', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
                {'label': 'Health Insurance Or Financing Scheme', 'borderColor': '#8a2be2', 'backgroundColor': '#8a2be2'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 12,
            },
            {
            'title': 'A. Reported Deaths',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAReportedDeaths',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 13,
            },
            {
            'title': 'B. Cause of Death',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSADeathCause',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_cause',
            'filter2_column': 'sex',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 14,
            },
            {
            'title': 'C. Reported Child and Infant Deaths',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAReportedDeaths',
            'x_column': 'year',
            'y_columns': ['children', 'infants'],
            'dataset_config': [
                {'label': 'Children', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Infants', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': 'Infants are children in the age group 0-1 years.',
            'display_order': 15,
            },
            {
            'title': 'D. Reported Infant Deaths',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantDeaths',
            'x_column': 'year',
            'y_columns': ['infant_deaths_reported'],
            'dataset_config': [
                {'label': 'Infant Deaths Reported', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Infants are children in the age group 0-1 years.',
            'display_order': 16,
            },
            {
            'title': 'E. Select Causes of Infant Death',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantDeaths2',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_cause',
            'filter2_column': '',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter1=True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Counts were calculated by applying cause percentages to reported infant deaths and rounding up to whole numbers. Totals may not match exactly due to rounding.',
            'display_order': 17,
            },
            {
            'title': 'F. Number of Children Diseased',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'HMISChildDisease2',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_disease',
            'filter2_column': '',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False, disable_all_filter1=True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 18,
            },
            {
            'title': 'G. Population with High Blood Sugar',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSHighBloodSugar',
            'x_column': 'year',
            'y_columns': ['men_high', 'women_high'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 19,
            },
            {
            'title': 'H. Population with Very High Blood Sugar',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSHighBloodSugar',
            'x_column': 'year',
            'y_columns': ['men', 'women'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 20,
            },
            {
            'title': 'I. Population with Mildly Elevated Blood Pressure',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSHypertension',
            'x_column': 'year',
            'y_columns': ['men_with_mildly_elevated_blood_pressure', 'women_with_mildly_elevated_blood_pressure'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 21,
            },
            {
            'title': 'J. Population with Moderately or Severely High Hypertension',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSHypertension',
            'x_column': 'year',
            'y_columns': ['men', 'women'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'In 2015 the “moderately or severely high” value was obtained by summing the moderately high and very high categories, whereas in 2019 it is reported directly as a single column.',
            'display_order': 22,
            },
            {
            'title': 'K. Women Examined for Cancer',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSCancerScreening2',
            'x_column': 'year',
            'y_columns': ['percentage'],
            'dataset_config': [
                {'label': 'Percentage', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_examination',
            'filter2_column': '',
            'show_filters': True,
            'chart_options': build_chart_options('Percentage', True,disable_all_filter1=True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 23,
            },
            {
            'title': 'L. Alcohol and Tobacco Consumption',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSTobaccoAlcohol',
            'x_column': 'year',
            'y_columns': ['men_tobacco', 'women_tobacco', 'men_alcohol', 'women_alcohol'],
            'dataset_config': [
                {'label': 'Men (Tobacco)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women (Tobacco)', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Men (Alcohol)', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Women (Alcohol)', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 24,
            },
            {
            'title': 'A. Reported Deliveries',
            'chapter_type': 'health',
            'chart_type': 'stackedBar',
            'data_source_table': 'HMISDeliveries',
            'x_column': 'year',
            'y_columns': ['institutional_deliveries', 'home_deliveries'],
            'dataset_config': [
                {'label': 'Institutional Deliveries', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Home Deliveries', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 25,
            },
            {
            'title': 'B. Institutional Births: Public vs Private',
            'chapter_type': 'health',
            'chart_type': 'percentStackedBar',
            'data_source_table': 'HMISDeliveries',
            'x_column': 'year',
            'y_columns': ['public_institutions', 'private_institutions'],
            'dataset_config': [
                {'label': 'Public Institutions', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private Institutions', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 26,
            },
            {
            'title': 'C. Home Births: Skilled vs Non-Skilled Attendants',
            'chapter_type': 'health',
            'chart_type': 'percentStackedBar',
            'data_source_table': 'HMISDeliveries',
            'x_column': 'year',
            'y_columns': ['trained_as_sbas', 'non_trained_as_sbas'],
            'dataset_config': [
                {'label': 'Trained as SBAs', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Non-Trained as SBAs', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'SBA stands for Skilled Birth Attendant and includes doctors, nurses, and auxiliary nurse midwives (ANMs). Non-Trained as SBAs include traditional birth attendants, who are not formally trained as SBAs.',
            'display_order': 27,
            },
            {
            'title': 'D. Live Birth Rate',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISDeliveries',
            'x_column': 'year',
            'y_columns': ['live_birth_rate'],
            'dataset_config': [
                {'label': 'Live Birth Rate', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Live birth rate is calculated by dividing the number of live births by the total of live and still births. Axis starts at 95% to highlight small differences more clearly.',
            'display_order': 28,
            },
            {
            'title': 'E. Still Birth Rate',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISDeliveries',
            'x_column': 'year',
            'y_columns': ['still_birth_rate'],
            'dataset_config': [
                {'label': 'Still Birth Rate', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Still birth rate is calculated by dividing the number of still births by the total of live and still births.',
            'display_order': 29,
            },
            {
            'title': 'F. Maternal Deaths',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'HMISMDeaths',
            'x_column': 'year',
            'y_columns': ['maternal_deaths'],
            'dataset_config': [
                {'label': 'Maternal Deaths', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 30,
            },
            {
            'title': 'G. Registered Births',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSARegisteredBirths',
            'x_column': 'year',
            'y_columns': ['boys', 'girls'],
            'dataset_config': [
                {'label': 'Boys', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Girls', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 31,
            },
            {
            'title': 'H. C-section Deliveries: Public vs Private',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISCSection',
            'x_column': 'year',
            'y_columns': ['public', 'private'],
            'dataset_config': [
                {'label': 'Public', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 32,
            },
            {
            'title': 'I. Institutional Deliveries through C-Section',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISCSection',
            'x_column': 'year',
            'y_columns': ['csection_share_of_institutional_deliveries'],
            'dataset_config': [
                {'label': 'C-Section Deliveries as a share of Reported Institutional Deliveries', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 33,
            },
            {
            'title': 'J. Deliveries through C-Section: Public vs Private Facilities',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISCSection',
            'x_column': 'year',
            'y_columns': ['public_facilities', 'private_facilities'],
            'dataset_config': [
                {'label': 'Public Facilities', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private Facilities', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Share of Total Deliveries', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 34,
            },
            {
            'title': 'K. Reported Abortions',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISAbortion',
            'x_column': 'year',
            'y_columns': ['abortions_reported'],
            'dataset_config': [
                {'label': 'Abortions Reported', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False,disable_all_filter2=True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 35,
            },
            {
            'title': 'L. Medical Terminations of Pregnancy: Public vs Private',
            'chapter_type': 'health',
            'chart_type': 'percentStackedBar',
            'data_source_table': 'HMISAbortion',
            'x_column': 'year',
            'y_columns': ['public', 'private'],
            'dataset_config': [
                {'label': 'Public', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True,disable_all_filter2=True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 36,
            },
            {
            'title': 'M. MTPs in Public Institutions before and after 12 Weeks',
            'chapter_type': 'health',
            'chart_type': 'percentStackedBar',
            'data_source_table': 'HMISAbortion',
            'x_column': 'year',
            'y_columns': ['up_to_12_weeks', 'more_than_12_weeks'],
            'dataset_config': [
                {'label': 'Up to 12 Weeks', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'More than 12 Weeks', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 37,
            },
            {
            'title': 'N. Average Out of Pocket Expenditure per Delivery in Public Health Facilities',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSDeliveryExpenditure',
            'x_column': 'year',
            'y_columns': ['avg_delivery_expenditure_in_public_facility'],
            'dataset_config': [
                {'label': 'Average Out Of Pocket Expenditure For Each Delivery In Public Health Facility', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Amount (RS)', False),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 38,
            },
            {
            'title': 'O. Registrations for Antenatal Care',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISAntenatalCare',
            'x_column': 'year',
            'y_columns': ['registered_for_antenatal_care'],
            'dataset_config': [
                {'label': 'Registered for Antenatal Care', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 39,
            },
            {
            'title': 'P. Antenatal Care Registrations Done in First Trimester',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISAntenatalCare',
            'x_column': 'year',
            'y_columns': ['pct_antenatal_care_first_trimester'],
            'dataset_config': [
                {'label': '% of Antenatal Care Registrations Done in First Trimester', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Share of Registrations', True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 40,
            },
            {
            'title': 'Q. Iron Folic Acid Consumption Among Pregnant Women',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSIFAConsumption',
            'x_column': 'year',
            'y_columns': ['hundred_days_or_more'],
            'dataset_config': [
                {'label': '100 Days or More', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Share of Pregnant Women', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'IFA is a supplementation of iron and folic acid intended to prevent anaemia and neural tube defects, and sustained consumption for at least 100 days is recommended for pregnant women.',
            'display_order': 41,
            },
            {
            'title': 'R. Access to Postnatal Care from Health Personnel Within 2 Days of Delivery',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSPostnatalCare',
            'x_column': 'year',
            'y_columns': ['mothers', 'children'],
            'dataset_config': [
                {'label': 'Mothers', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Children', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 42,
            },
            {
            'title': 'S. Children Breastfed within One Hour of Birth',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSDiet',
            'x_column': 'year',
            'y_columns': ['breastfed_within_one_hour_of_birth'],
            'dataset_config': [
                {'label': 'Breastfed Within One Hour Of Birth', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage',True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 43,
            },
            {
            'title': 'T. Children (6-23 months) Receiving an Adequate Diet',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSDiet',
            'x_column': 'year',
            'y_columns': ['receiving_an_adequate_diet'],
            'dataset_config': [
                {'label': 'Receiving An Adequate Diet', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'For children aged 6–23 months, NFHS defines an “adequate diet” as receiving the minimum acceptable diet. This involves meeting both minimum dietary diversity (foods from ≥5 of 8 groups in the previous day) and minimum meal frequency appropriate for age and breastfeeding status (plus ≥2 milk feeds if non-breastfed).',
            'display_order': 44,
            },
            {
            'title': 'U. Sex Ratio at Birth',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISSexRatio',
            'x_column': 'year',
            'y_columns': ['sex_ratio_at_birth'],
            'dataset_config': [
                {'label': 'Sex Ratio At Birth', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('No. of Females (per thousand males)', False),
            'description': ' Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 45,
            },
            {
            'title': 'V. Births Registered with Civil Authority',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSBirths',
            'x_column': 'year',
            'y_columns': ['births_registered_with_civil_authority'],
            'dataset_config': [
                {'label': 'Births Registered with Civil Authority', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 46,
            },
            {
            'title': 'W. Institutional Deliveries through C-section',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSCSection',
            'x_column': 'year',
            'y_columns': ['births_delivered_by_caesarean_section'],
            'dataset_config': [
                {'label': 'Births Delivered By Caesarean Section', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 47,
            },
            {
            'title': 'X. C-section Deliveries: Public vs Private',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSCSection',
            'x_column': 'year',
            'y_columns': ['public_health_facility', 'private_health_facility'],
            'dataset_config': [
                {'label': 'Public Health Facility', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private Health Facility', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 48,
            },
            {
            'title': 'A. Population Using Family Planning Methods',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['use_of_any_family_planning_methods', 'any_modern_family_planning_method'],
            'dataset_config': [
                {'label': 'Use of Any Family Planning Methods', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Any Modern Family Planning Method', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'NFHS counts “any family planning method” as use of either a modern method (female/male sterilization, pill, IUD/PPIUD/CuT, injectable, implant, condom, LAM, emergency contraception) or a traditional method (rhythm/periodic abstinence, withdrawal, folk methods), while “modern family planning method” counts use of only the modern subset and excludes all traditional methods.',
            'display_order': 49,
            },
            {
            'title': 'B. Usage Rate of Select Family Planning Methods',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['female_sterilization', 'male_sterilization', 'iud_or_ppiud', 'birth_control_pill', 'condom'],
            'dataset_config': [
                {'label': 'Female Sterilization', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Male Sterilization', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'IUD Or PPIUD', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Birth Control Pill', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
                {'label': 'Condom', 'borderColor': '#8a2be2', 'backgroundColor': '#8a2be2'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'NFHS shows this rate based on whether married women (in the age group 15-49 years) use these methods as one of their family planning methods.',
            'display_order': 50,
            },
            {
            'title': 'C. Sterilizations Conducted (Public vs Private Facilities)',
            'chapter_type': 'health',
            'chart_type': 'stackedBar',
            'data_source_table': 'HMISFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['public_institutions', 'private_institutions'],
            'dataset_config': [
                {'label': 'Public Institutions', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private Institutions', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 51,
            },
            {
            'title': 'D. Vasectomies',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['vasectomies'],
            'dataset_config': [
                {'label': 'Vasectomies', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 52,
            },
            {
            'title': 'E. Tubectomies',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['tubectomies'],
            'dataset_config': [
                {'label': 'Tubectomies', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 53,
            },
            {
            'title': 'F. Contraceptives Distributed',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISContraceptives',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_contraceptive',
            'filter2_column': '',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False,disable_all_filter1=True),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 54,
            },
            {
            'title': 'G. IUD Insertions: Public vs Private',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['public_facilities', 'private_facilities'],
            'dataset_config': [
                {'label': 'Public Facilities', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private Facilities', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 55,
            },
            {
            'title': 'H. Female Sterilization Rate',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['female_sterilization'],
            'dataset_config': [
                {'label': 'Female Sterilization', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'NFHS provides these values only for married women within the age group 15-49 years.',
            'display_order': 56,
            },
            {
            'title': 'I. Women’s Unmet Need for Family Planning',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSFamilyPlanning',
            'x_column': 'year',
            'y_columns': ['married_women_15_49_years', 'all_women'],
            'dataset_config': [
                {'label': 'Married Women (15-49 Years)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'All Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 57,
            },
            {
            'title': 'J. Fertile Couples in Family Welfare Programs',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAFamilyWelfarePrograms',
            'x_column': 'year',
            'y_columns': ['fertile_couples'],
            'dataset_config': [
                {'label': 'Fertile Couples', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False, disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 58,
            },
            {
            'title': 'K. Family Welfare Centers',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAFamilyWelfarePrograms',
            'x_column': 'year',
            'y_columns': ['family_welfare_centers'],
            'dataset_config': [
                {'label': 'Family Welfare Centers', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False, disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 59,
            },
            {
            'title': 'L. Progress of Family Welfare Programs',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAFamilyWelfarePrograms',
            'x_column': 'year',
            'y_columns': ['male_sterilization_numbers', 'female_sterilization_numbers', 'iuds_inserted', 'other_family_planning_methods_used'],
            'dataset_config': [
                {'label': 'Male Sterilization', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Female Sterilization', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'IUDs Inserted', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Other Family Planning Methods Used', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'rural_urban',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False, disable_all_filter2=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 60,
            },
            {
            'title': 'A. Vaccinations under the Maternal and Childcare Program',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAVaccines',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'taluka',
            'filter2_column': 'select_vaccine',
            'show_filters': True,
            'chart_options': {**build_chart_options('Number', False, disable_all_filter2=True), 'fixed_filters': {'rural_urban': 'Total'}},
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 61,
            },
            {
            'title': 'B. Infants Given the Oral Polio Vaccine',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['oral_polio_vaccine'],
            'dataset_config': [
                {'label': 'Oral Polio Vaccine', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 62,
            },
            {
            'title': 'C. Infants Given the Bacillus Calmette Guerin (BCG) Vaccine',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['bcg'],
            'dataset_config': [
                {'label': 'Bacillus Calmette Guerin (BCG)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 63,
            },
            {
            'title': 'D. Infants Given Hepatitis Vaccine (Birth Dose)',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['hepatitis_birth_dose'],
            'dataset_config': [
                {'label': 'Hepatitis (Birth Dose)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 64,
            },
            {
            'title': 'E. Infants Given the Pentavalent Vaccines',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['pentavalent_1', 'pentavalent_2', 'pentavalent_3'],
            'dataset_config': [
                {'label': 'Pentavalent-1', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Pentavalent-2', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Pentavalent-3', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Pentavalent is a combination vaccine that protects infants against five diseases: diphtheria, pertussis (whooping cough), tetanus, hepatitis B, and Haemophilus influenzae type b (Hib). The numbers represent the dose order of the vaccine.',
            'display_order': 65,
            },
            {
            'title': 'F. Infants Given the Measles or Measles Rubella Vaccines',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['measles', 'measles_rubella'],
            'dataset_config': [
                {'label': 'Measles', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Measles Rubella', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 66,
            },
            {
            'title': 'G. Infants Given the Rotavirus Vaccines',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['rotavirus_1st_dose', 'rotavirus_2nd_dose', 'rotavirus_3rd_dose'],
            'dataset_config': [
                {'label': 'Rotavirus (1st Dose)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Rotavirus (2nd Dose)', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Rotavirus (3rd Dose)', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 67,
            },
            {
            'title': 'H. Fully Immunized Children',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISInfantVaccinations',
            'x_column': 'year',
            'y_columns': ['fully_immunized_children'],
            'dataset_config': [
                {'label': 'Fully Immunized Children', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Fully immunized is defined as a child having received BCG, measles vaccine, and three doses each of polio and DPT.',
            'display_order': 68,
            },
            {
            'title': 'I. Adverse Effects of Immunization',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISIV2',
            'x_column': 'year',
            'y_columns': ['number'],
            'dataset_config': [
                {'label': 'Number', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_effect',
            'filter2_column': '',
            'show_filters': True,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Total value for adverse effects is calculated by adding up cases of abscess, deaths, and other complications.',
            'display_order': 69,
            },
            {
            'title': 'J. Percentage of Children Fully Immunized',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSVaccinations',
            'x_column': 'year',
            'y_columns': ['fully_immunized'],
            'dataset_config': [
                {'label': 'Fully Immunized', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Fully immunized is defined as a child having received BCG, measles vaccine, and three doses each of polio and DPT.',
            'display_order': 70,
            },
            {
            'title': 'K. Vaccination Rate (Children Aged 12 to 23 months)',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSVaccinations',
            'x_column': 'year',
            'y_columns': ['bcg', 'polio_vaccine', 'dpt_vaccine', 'measles_vaccine', 'hepatitis_b_vaccine'],
            'dataset_config': [
                {'label': 'Bacillus Calmette Guerin (BCG)', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Polio Vaccine', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'DPT Vaccine', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Measles Vaccine', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
                {'label': 'Hepatitis B Vaccine', 'borderColor': '#8a2be2', 'backgroundColor': '#8a2be2'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 71,
            },
            {
            'title': 'L. Children Primarily Vaccinated in (Public vs Private Health Facilities)',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSVaccinations',
            'x_column': 'year',
            'y_columns': ['public_health_facility', 'private_health_facility'],
            'dataset_config': [
                {'label': 'Public Health Facility', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Private Health Facility', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 72,
            },
            {
            'title': 'A. Children with Nutritional Deficits or Excess',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSMalnutrition',
            'x_column': 'year',
            'y_columns': ['stunted', 'wasted', 'severely_wasted', 'underweight', 'overweight'],
            'dataset_config': [
                {'label': 'Stunted', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Wasted', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Severely Wasted', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Underweight', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
                {'label': 'Overweight', 'borderColor': '#8a2be2', 'backgroundColor': '#8a2be2'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': 'Stunted means low height for age, wasted means low weight for height, severely wasted means very low weight for height, underweight means low weight for age, and overweight means high weight for height.',
            'display_order': 73,
            },
            {
            'title': 'B. Population Overweight or Obese',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSOverweight',
            'x_column': 'year',
            'y_columns': ['men', 'women'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 74,
            },
            {
            'title': 'C. Population with Low BMI',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSLowBMI',
            'x_column': 'year',
            'y_columns': ['men', 'women'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 75,
            },
            {
            'title': 'D. Prevalence of Anaemia',
            'chapter_type': 'health',
            'chart_type': 'bar',
            'data_source_table': 'NFHSAnaemia',
            'x_column': 'year',
            'y_columns': ['men', 'women', 'children', 'non_pregnant_women', 'pregnant_women'],
            'dataset_config': [
                {'label': 'Men', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
                {'label': 'Women', 'borderColor': '#e9ba5d', 'backgroundColor': '#e9ba5d'},
                {'label': 'Children', 'borderColor': '#e46e53', 'backgroundColor': '#e46e53'},
                {'label': 'Non-Pregnant Women', 'borderColor': '#00a3e0', 'backgroundColor': '#00a3e0'},
                {'label': 'Pregnant Women', 'borderColor': '#8a2be2', 'backgroundColor': '#8a2be2'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Percentage', True),
            'description': 'National Family Health Survey (NFHS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 76,
            },
            {
            'title': 'E. Moderately Anaemic Women',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISAnaemia',
            'x_column': 'year',
            'y_columns': ['moderately_anaemic_women'],
            'dataset_config': [
                {'label': 'Moderately Anaemic Women', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 77,
            },
            {
            'title': 'F. Women with Severe Anaemia being Treated at an Institution',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'HMISAnaemia',
            'x_column': 'year',
            'y_columns': ['women_with_severe_anemia_treated_at_institution'],
            'dataset_config': [
                {'label': 'Women Having Tested With Severe Anemia and Are Being Treated at an Institution', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': '',
            'filter2_column': '',
            'show_filters': False,
            'chart_options': build_chart_options('Number', False),
            'description': 'Health Management Information System (HMIS), accessed through National Data and Analytics Platform (NDAP)',
            'additional_info': '',
            'display_order': 78,
            },
            {
            'title': 'G. Malnourishment Among Infants in Anganwadis',
            'chapter_type': 'health',
            'chart_type': 'line',
            'data_source_table': 'DSAMalnutrition2',
            'x_column': 'year',
            'y_columns': ['percentage'],
            'dataset_config': [
                {'label': 'Percentage', 'borderColor': '#1a4570', 'backgroundColor': '#1a4570'},
            ],
            'main_filter_column': 'district',
            'filter1_column': 'select_variable',
            'filter2_column': 'taluka',
            'show_filters': True,
            'chart_options': build_chart_options('Percentage', True, disable_all_filter1=True),
            'description': 'District Statistical Abstracts',
            'additional_info': '',
            'display_order': 79,
            },
        ]
        count = 0
        updated = 0
        for config in templates:
            obj, created = ChartTemplate.objects.update_or_create(
                title=config["title"],
                chapter_type=config["chapter_type"],
                defaults=config
            )
            if created:
                count += 1
                self.stdout.write(f"  [NEW] {obj.title}")
            else:
                updated += 1
                self.stdout.write(f"  [UPD] {obj.title}")

        expected_titles = {config["title"] for config in templates}
        stale_titles = list(
            ChartTemplate.objects
            .filter(chapter_type="health")
            .exclude(title__in=expected_titles)
            .values_list("title", flat=True)
        )
        if stale_titles:
            self.stdout.write(self.style.WARNING(
                "\nStale health templates found (not touched by this command):\n"
                + "\n".join(f"  - {title}" for title in stale_titles)
            ))

        self.stdout.write(self.style.SUCCESS(
            f"\nDone! Processed {len(templates)} templates. ({count} new, {updated} updated)"
        ))