# Generated by Django 5.2.3 on 2025-08-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_remove_profile_user_type_profile_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Can manage users and system settings'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_content_editor',
            field=models.BooleanField(default=False, help_text='Can create and edit content'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_reviewer',
            field=models.BooleanField(default=False, help_text='Can review and approve content'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Has all permissions'),
        ),
    ]
