# Generated by Django 5.2.3 on 2025-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_roles_profile_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
