# Generated by Django 5.2.3 on 2025-07-29 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('app_label', models.CharField(max_length=50)),
                ('chapter_id', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=255)),
                ('edit_type', models.CharField(choices=[('correction', 'Correction of factual error'), ('addition', 'Addition of new information'), ('clarification', 'Clarification of existing content'), ('update', 'Update outdated information'), ('other', 'Other')], max_length=20)),
                ('current_text', models.TextField(blank=True)),
                ('suggested_text', models.TextField()),
                ('reason', models.TextField()),
                ('sources', models.TextField(blank=True)),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to='suggest_edits/')),
                ('notify_on_review', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggest Edit',
                'verbose_name_plural': 'Suggest Edits',
                'ordering': ['-created_at'],
            },
        ),
    ]
