# Generated by Django 5.2.3 on 2025-08-30 06:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Enter the careers text here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Careers_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('department', models.CharField(help_text='Department/Team', max_length=100)),
                ('location', models.CharField(help_text='Job location', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', help_text='Type of employment', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], default='entry', help_text='Required experience level', max_length=20)),
                ('salary_range', models.CharField(blank=True, help_text='Salary range (optional)', max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(help_text='Job description and responsibilities')),
                ('requirements', tinymce.models.HTMLField(help_text='Job requirements and qualifications')),
                ('benefits', tinymce.models.HTMLField(blank=True, help_text='Benefits and perks (optional)', null=True)),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this job posting active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Post',
                'verbose_name_plural': 'Career Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Enter the disclaimer text here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Enter the partnership text here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Enter the project text here.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Enter the terms and conditions text here.', null=True)),
            ],
        ),
    ]
