# Generated by Django 5.1.7 on 2025-06-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Demography', 'Demography'), ('Agriculture', 'Agriculture'), ('Livestock & Fisheries', 'Livestock & Fisheries'), ('Education', 'Education'), ('Health', 'Health'), ('Environment', 'Environment'), ('Industry', 'Industry'), ('Labour', 'Labour'), ('Police & Judiciary', 'Police & Judiciary'), ('Transport & Communication', 'Transport & Communication'), ('Revenue & Expenditure', 'Revenue & Expenditure'), ('Schemes', 'Schemes')], max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistical_chapters', to='home.district')),
            ],
            options={
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StatisticalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('heading', 'Heading'), ('subheading', 'Subheading'), ('text', 'Text'), ('image', 'Image')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='statistical_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='statistic.statisticalchapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
