# Generated by Django 5.2.3 on 2025-07-08 13:36

import django.db.models.deletion
import statistic.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatisticalChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Demography', 'Demography'), ('Education', 'Education'), ('Environment', 'Environment'), ('Health', 'Health'), ('Industry', 'Industry'), ('Labour', 'Labour'), ('Livestock & Fisheries', 'Livestock & Fisheries'), ('Police & Judiciary', 'Police & Judiciary'), ('Revenue & Expenditure', 'Revenue & Expenditure'), ('Transport & Communication', 'Transport & Communication')], max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistical_chapters', to='home.district')),
            ],
            options={
                'verbose_name': 'Statistical Chapter',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChartBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('title', models.CharField(blank=True, help_text="Title of the chart e.g., 'Population Growth'", max_length=255, null=True)),
                ('chart_html_file', models.FileField(help_text='Upload on The PreGenrated  .html File for the Chart', upload_to=statistic.models.get_statistic_chart_path)),
            ],
            options={
                'verbose_name': 'Chart Block (HTML Upload)',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='HeadingBlockOne',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255, verbose_name='Heading 1')),
            ],
            options={
                'verbose_name': 'Heading 1',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='HeadingBlockThree',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255, verbose_name='Heading 3')),
            ],
            options={
                'verbose_name': 'Heading 3',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='HeadingBlockTwo',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255, verbose_name='Heading 2')),
            ],
            options={
                'verbose_name': 'Heading 2',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('image', models.ImageField(upload_to=statistic.models.get_seo_image_path, verbose_name='Original Image')),
                ('caption', models.CharField(blank=True, max_length=4000)),
                ('alt_text', models.CharField(help_text='Accessibility text for screen readers.', max_length=4000)),
                ('img_ref', models.CharField(blank=True, help_text='Reference for the image source', max_length=4000, null=True)),
            ],
            options={
                'verbose_name': 'Image Block',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='ParagraphBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('content', tinymce.models.HTMLField(verbose_name='formatted text for context')),
            ],
            options={
                'verbose_name': 'Paragraph Block',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='ReferenceBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.TextField()),
                ('link', models.URLField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'verbose_name': 'Reference Block',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.AddField(
            model_name='statisticcontentblock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='statistic.statisticalchapter'),
        ),
    ]
