# Generated by Django 5.1.6 on 2025-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticalchapter',
            name='name',
            field=models.CharField(choices=[('Demography', 'Demography'), ('Agriculture', 'Agriculture'), ('Livestock & Fisheries', 'Livestock & Fisheries'), ('Education', 'Education'), ('Health', 'Health'), ('Environment', 'Environment'), ('Industry', 'Industry'), ('Labour', 'Labour'), ('Police & Judiciary', 'Police & Judiciary'), ('Transport & Communication', 'Transport & Communication'), ('Revenue & Expenditure', 'Revenue & Expenditure'), ('Schemes', 'Schemes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='statisticalchapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
