# Generated by Django 5.1.7 on 2025-06-15 16:18

import django.db.models.deletion
import statistic.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='statisticalchapter',
            options={'ordering': ['name'], 'verbose_name': 'Statistical Chapter'},
        ),
        migrations.AddField(
            model_name='statisticalchapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='statisticalchapter',
            name='name',
            field=models.CharField(choices=[('Demography', 'Demography'), ('Agriculture', 'Agriculture'), ('Livestock & Fisheries', 'Livestock & Fisheries'), ('Education', 'Education'), ('Health', 'Health'), ('Environment', 'Environment'), ('Industry', 'Industry'), ('Labour', 'Labour'), ('Police & Judiciary', 'Police & Judiciary'), ('Transport & Communication', 'Transport & Communication'), ('Revenue & Expenditure', 'Revenue & Expenditure'), ('Schemes', 'Schemes')], max_length=200),
        ),
        migrations.AlterField(
            model_name='statisticalchapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ChartBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('title', models.CharField(blank=True, help_text="Title of the chart e.g., 'Population Growth'", max_length=255, null=True)),
                ('chart_html_file', models.FileField(help_text='Upload on The PreGenrated  .html File for the Chart', upload_to=statistic.models.get_statistic_chart_path)),
            ],
            options={
                'verbose_name': 'Chart Block (HTML Upload)',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='HeadingBlockOne',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255, verbose_name='Heading 1')),
            ],
            options={
                'verbose_name': 'Heading 1',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='HeadingBlockThree',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255, verbose_name='Heading 3')),
            ],
            options={
                'verbose_name': 'Heading 3',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='HeadingBlockTwo',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255, verbose_name='Heading 2')),
            ],
            options={
                'verbose_name': 'Heading 2',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('image', models.ImageField(upload_to=statistic.models.get_seo_image_path)),
                ('caption', models.CharField(blank=True, max_length=4000)),
                ('alt_text', models.CharField(help_text='Accessibility text for screen readers.', max_length=4000)),
            ],
            options={
                'verbose_name': 'Image Block',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='ParagraphBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('content', tinymce.models.HTMLField(verbose_name='formatted text for context')),
            ],
            options={
                'verbose_name': 'Paragraph Block',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.CreateModel(
            name='ReferenceBlock',
            fields=[
                ('statisticcontentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statisticcontentblock')),
                ('text', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reference Block',
            },
            bases=('statistic.statisticcontentblock',),
        ),
        migrations.AddField(
            model_name='statisticcontentblock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='statistic.statisticalchapter'),
        ),
        migrations.AddField(
            model_name='statisticcontentblock',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='StatisticalSection',
        ),
    ]
