# Generated by Django 5.2.3 on 2025-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceblock',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='referenceblock',
            name='text',
            field=models.URLField(),
        ),
    ]
