# Generated by Django 5.2.3 on 2025-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_referenceblock_link_alter_referenceblock_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceblock',
            name='text',
            field=models.TextField(),
        ),
    ]
