# Generated by Django 5.2.3 on 2025-06-24 18:37

import statistic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_statisticalchapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(upload_to=statistic.models.get_seo_image_path, verbose_name='Original Image'),
        ),
    ]
