# Generated by Django 5.2.3 on 2025-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_statisticalchapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticalchapter',
            name='name',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Demography', 'Demography'), ('Education', 'Education'), ('Environment', 'Environment'), ('Health', 'Health'), ('Industry', 'Industry'), ('Labour', 'Labour'), ('Livestock & Fisheries', 'Livestock & Fisheries'), ('Police & Judiciary', 'Police & Judiciary'), ('Revenue & Expenditure', 'Revenue & Expenditure'), ('Transport & Communication', 'Transport & Communication')], max_length=200),
        ),
    ]
