# Generated by Django 5.2.3 on 2025-09-08 04:35

from django.db import migrations

def update_labour_to_lobar(apps, schema_editor):
    StatisticalChapter = apps.get_model('statistic', 'StatisticalChapter')
    # Update all chapters with name 'Labour' to 'Lobar'
    StatisticalChapter.objects.filter(name='Labour').update(name='Lobar')

class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_alter_statisticalchapter_name'),
    ]

    operations = [
        migrations.RunPython(update_labour_to_lobar)
    ]
