# Generated by Django 5.2.3 on 2025-07-09 15:00

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('introduction', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Introduction')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('state_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='district_images/originals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Original Image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictQuickFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_facts', to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_content', models.TextField(verbose_name='SVG Content')),
                ('district_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='districtsvg', to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='GIFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='gif_images/originals/', validators=[django.core.validators.FileExtensionValidator(['gif'])], verbose_name='Original GIF')),
                ('optimized_video', models.FileField(blank=True, editable=False, null=True, upload_to='gif_images/videos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_images', to='home.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='home.state'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
    ]
