# Generated by Django 5.2.3 on 2025-06-23 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='districtsection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='districtsection',
            name='district',
        ),
        migrations.RemoveField(
            model_name='sectionimage',
            name='section',
        ),
        migrations.CreateModel(
            name='GIFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gif_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('gifimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_images', to='home.district')),
            ],
        ),
        migrations.DeleteModel(
            name='SectionParagraph',
        ),
        migrations.DeleteModel(
            name='DistrictSection',
        ),
        migrations.DeleteModel(
            name='SectionImage',
        ),
    ]
