# Generated by Django 5.2.3 on 2025-08-17 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_type', models.CharField(choices=[('cultural', 'Cultural Chapter'), ('statistical', 'Statistical Chapter')], max_length=20)),
                ('chapter_name', models.CharField(max_length=200)),
                ('ready_for_review', models.BooleanField(default=False, verbose_name='Ready for Review')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_reviews', to='home.district')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Chapter Review',
                'verbose_name_plural': 'Chapter Reviews',
                'ordering': ['-updated_at'],
                'unique_together': {('chapter_type', 'chapter_name', 'district')},
            },
        ),
    ]
