# Generated by Django 5.1.7 on 2025-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quickfacticon_alter_district_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtquickfact',
            name='icon',
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='districtimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='districtparagraph',
            options={},
        ),
        migrations.AlterModelOptions(
            name='districtquickfact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='districtsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionparagraph',
            options={},
        ),
        migrations.RemoveField(
            model_name='districtimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='districtparagraph',
            name='order',
        ),
        migrations.RemoveField(
            model_name='districtquickfact',
            name='order',
        ),
        migrations.RemoveField(
            model_name='districtsection',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sectionimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sectionparagraph',
            name='order',
        ),
        migrations.AlterField(
            model_name='districtquickfact',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='QuickFactIcon',
        ),
    ]
