# Generated by Django 5.2.3 on 2025-06-24 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_districtsection_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifimage',
            name='image',
        ),
        migrations.AddField(
            model_name='gifimage',
            name='optimized_video',
            field=models.FileField(blank=True, null=True, upload_to='gif_images/videos/'),
        ),
        migrations.AddField(
            model_name='gifimage',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='gif_images/originals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Original GIF'),
        ),
        migrations.AlterField(
            model_name='districtimage',
            name='image',
            field=models.ImageField(upload_to='district_images/originals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Original Image'),
        ),
    ]
