# Generated by Django 5.2.3 on 2025-08-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chapterreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterReview',
        ),
    ]
