# Generated by Django 5.2.3 on 2025-06-24 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_gifimage_image_gifimage_optimized_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtimage',
            name='image',
        ),
        migrations.AddField(
            model_name='districtimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='district_images/originals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Original Image'),
        ),
        migrations.AlterField(
            model_name='gifimage',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='gif_images/originals/', validators=[django.core.validators.FileExtensionValidator(['gif'])], verbose_name='Original GIF'),
        ),
    ]
