# Generated by Django 5.2.3 on 2025-08-17 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('home', '0003_delete_chapterreview'),
        ('statistic', '0003_alter_referenceblock_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_for_review', models.BooleanField(default=False, verbose_name='Ready for Review')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Developer Reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_created_reviews', to=settings.AUTH_USER_MODEL)),
                ('cultural_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_check', to='culture.culturalchapter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_reviewed_chapters', to=settings.AUTH_USER_MODEL)),
                ('statistical_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_check', to='statistic.statisticalchapter')),
            ],
            options={
                'verbose_name': 'Developer Check',
                'verbose_name_plural': 'Developer Checks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_for_review', models.BooleanField(default=False, verbose_name='Ready for Final Review')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Final Reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_created_reviews', to=settings.AUTH_USER_MODEL)),
                ('cultural_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_check', to='culture.culturalchapter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reviewed_chapters', to=settings.AUTH_USER_MODEL)),
                ('statistical_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_check', to='statistic.statisticalchapter')),
            ],
            options={
                'verbose_name': 'Final Check',
                'verbose_name_plural': 'Final Checks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UploaderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_for_review', models.BooleanField(default=False, verbose_name='Ready for Upload Review')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Upload Reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_created_reviews', to=settings.AUTH_USER_MODEL)),
                ('cultural_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_check', to='culture.culturalchapter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_reviewed_chapters', to=settings.AUTH_USER_MODEL)),
                ('statistical_chapter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_check', to='statistic.statisticalchapter')),
            ],
            options={
                'verbose_name': 'Uploader Check',
                'verbose_name_plural': 'Uploader Checks',
                'ordering': ['-updated_at'],
            },
        ),
    ]
