# Generated by Django 5.1.7 on 2025-06-04 06:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_districtquickfact_icon_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='introduction',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtparagraph',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionparagraph',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
