# Generated by Django 5.1.7 on 2025-06-04 07:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_district_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='hover_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='state',
            name='svg_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='introduction',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='districtparagraph',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='sectionparagraph',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
