# Generated by Django 5.2.3 on 2025-08-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_developercheck_finalcheck_uploadercheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploaderCheck',
        ),
    ]
