# Generated by Django 5.2.3 on 2025-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_districtimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifimage',
            old_name='gifimage',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='gifimage',
            name='optimized_video',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='gif_images/videos/'),
        ),
    ]
