# Generated by Django 5.1.7 on 2025-06-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_state_hover_info_state_state_code_state_svg_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='hover_info',
        ),
        migrations.RemoveField(
            model_name='state',
            name='svg_path',
        ),
        migrations.AddField(
            model_name='district',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='district',
            name='svg_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
