# Generated by Django 5.2.3 on 2025-06-24 11:09

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_gifimage_gifimage_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.DistrictImage.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Original Image'),
        ),
    ]
