# Generated by Django 5.2.3 on 2025-06-24 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_districtimage_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='district_images/originals/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Original Image'),
        ),
    ]
