# Generated by Django 5.1.7 on 2025-06-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_state_hover_info_remove_state_svg_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='district',
            name='svg_path',
        ),
        migrations.CreateModel(
            name='DistrictSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_content', models.TextField(verbose_name='SVG Content')),
                ('district_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='districtsvg', to='home.district')),
            ],
        ),
    ]
