# Generated by Django 5.1.7 on 2025-06-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culture', '0010_headingblockthree'),
        ('home', '0001_initial'),
        ('statistic', '0002_statisticcontentblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidePanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True, verbose_name='Word')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cultural_chapter', models.ForeignKey(blank=True, help_text='Choose a Cultural Chapter if this entry is related to one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultural_chapters', to='culture.culturalchapter', verbose_name='Cultural Chapter')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidepanal_entries', to='home.district', verbose_name='District')),
                ('statistical_chapter', models.ForeignKey(blank=True, help_text='Choose a Statistical Chapter if this entry is related to one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistical_chapters', to='statistic.statisticalchapter', verbose_name='Statistical Chapter')),
            ],
            options={
                'verbose_name': 'Side Panel Entry',
                'verbose_name_plural': 'Side Panel Entries',
                'ordering': ['word'],
                'unique_together': {('word', 'cultural_chapter', 'statistical_chapter')},
            },
        ),
    ]
