# Generated by Django 5.2.3 on 2025-07-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culture', '__first__'),
        ('statistic', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalSidePanelManager',
            fields=[
            ],
            options={
                'verbose_name': 'Cultural Side Panel Manager',
                'verbose_name_plural': 'Cultural Side panel Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('culture.culturalchapter',),
        ),
        migrations.CreateModel(
            name='StatisticalSidePanelManager',
            fields=[
            ],
            options={
                'verbose_name': 'Statistical Side Panel Manager',
                'verbose_name_plural': 'Statistical Side Panel Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('statistic.statisticalchapter',),
        ),
        migrations.CreateModel(
            name='CulturalSidePanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Word')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cultural_chapter', models.ForeignKey(blank=True, help_text='Choose a Cultural Chapter if this entry is related to one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultural_chapters', to='culture.culturalchapter', verbose_name='Cultural Chapter')),
            ],
            options={
                'verbose_name_plural': 'Cultural Side Panals all records',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='StatisticalSidePanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Statistical Word')),
                ('definition', models.TextField(verbose_name='Statistical Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('statistical_chapter', models.ForeignKey(blank=True, help_text='Choose a Statistical Chapter if this entry is related to one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistical_chapters', to='statistic.statisticalchapter', verbose_name='Statistical Chapter')),
            ],
            options={
                'verbose_name_plural': 'Stat Side Panals all records',
                'ordering': ['word'],
            },
        ),
    ]
