# Generated by Django 5.1.7 on 2025-06-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0010_headingblockthree'),
        ('sidepanal', '0001_initial'),
        ('statistic', '0002_statisticcontentblock_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sidepanal',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sidepanal',
            name='word',
            field=models.CharField(max_length=200, verbose_name='Word'),
        ),
        migrations.AlterUniqueTogether(
            name='sidepanal',
            unique_together={('word', 'cultural_chapter'), ('word', 'statistical_chapter')},
        ),
    ]
