# Generated by Django 5.2.3 on 2025-09-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidepanal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalsidepanal',
            name='cultural_chapter',
        ),
        migrations.RemoveField(
            model_name='statisticalsidepanal',
            name='statistical_chapter',
        ),
        migrations.DeleteModel(
            name='CulturalSidePanelManager',
        ),
        migrations.DeleteModel(
            name='StatisticalSidePanelManager',
        ),
        migrations.DeleteModel(
            name='CulturalSidePanal',
        ),
        migrations.DeleteModel(
            name='StatisticalSidePanal',
        ),
    ]
