# Generated by Django 5.1.7 on 2025-06-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidepanal', '0003_culturalsidepanal_statisticalsidepanal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalsidepanal',
            options={'ordering': ['word']},
        ),
        migrations.AlterModelOptions(
            name='statisticalsidepanal',
            options={'ordering': ['word']},
        ),
        migrations.RemoveField(
            model_name='culturalsidepanal',
            name='district',
        ),
        migrations.RemoveField(
            model_name='statisticalsidepanal',
            name='district',
        ),
    ]
