# Generated by Django 5.2.3 on 2025-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidepanal', '0004_alter_culturalsidepanal_options_and_more'),
        ('statistic', '0004_alter_imageblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalSidePanelManager',
            fields=[
            ],
            options={
                'verbose_name': 'Statistical Side Panel Manager',
                'verbose_name_plural': 'Statistical Side Panel Managers (by Chapter)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('statistic.statisticalchapter',),
        ),
    ]
