# Generated by Django 5.2.3 on 2025-06-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0012_alter_imageblock_image'),
        ('sidepanal', '0005_statisticalsidepanelmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalSidePanelManager',
            fields=[
            ],
            options={
                'verbose_name': 'Cultural Side Panel Manager',
                'verbose_name_plural': 'Cultural panel Managers (by Chapter)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('culture.culturalchapter',),
        ),
    ]
