# Generated by Django 5.2.3 on 2025-06-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidepanal', '0006_culturalsidepanelmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalsidepanelmanager',
            options={'verbose_name': 'Cultural Side Panel Manager', 'verbose_name_plural': 'Cultural Side panel Managers'},
        ),
        migrations.AlterModelOptions(
            name='statisticalsidepanelmanager',
            options={'verbose_name': 'Statistical Side Panel Manager', 'verbose_name_plural': 'Statistical Side Panel Managers'},
        ),
    ]
