# Generated by Django 5.2.3 on 2025-06-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidepanal', '0007_alter_culturalsidepanelmanager_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalsidepanal',
            options={'ordering': ['word'], 'verbose_name_plural': 'Cultural Side Panals all records'},
        ),
        migrations.AlterModelOptions(
            name='statisticalsidepanal',
            options={'ordering': ['word'], 'verbose_name_plural': 'Stat Side Panals all records'},
        ),
    ]
