# Generated by Django 5.1.7 on 2025-06-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0007_remove_district_district_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeadingBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Heading Block',
            },
            bases=('culture.contentblock',),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('image', models.ImageField(upload_to='culture/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(help_text='Accessibility text for screen readers.', max_length=255)),
            ],
            options={
                'verbose_name': 'Image Block',
            },
            bases=('culture.contentblock',),
        ),
        migrations.CreateModel(
            name='ParagraphBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('content', models.TextField(help_text='Formatted text, lists, and tables go here.')),
            ],
            options={
                'verbose_name': 'Paragraph Block',
            },
            bases=('culture.contentblock',),
        ),
        migrations.CreateModel(
            name='ReferenceBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('text', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reference Block',
            },
            bases=('culture.contentblock',),
        ),
        migrations.CreateModel(
            name='CulturalChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Food', 'Food'), ('People', 'People'), ('Language', 'Language'), ('Artforms', 'Artforms'), ('Stories', 'Stories'), ('Cultural Sites', 'Cultural Sites'), ('Architecture', 'Architecture'), ('Sports & Games', 'Sports & Games'), ('Festivals & Fairs', 'Festivals & Fairs'), ('Political History', 'Political History'), ('Markets', 'Markets'), ('Local Politics', 'Local Politics')], max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultural_chapters', to='home.district')),
            ],
            options={
                'verbose_name': 'Cultural Chapter',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='culture.culturalchapter'),
        ),
    ]
