# Generated by Django 5.1.7 on 2025-06-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingBlockTwo',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Heading 2',
            },
            bases=('culture.contentblock',),
        ),
        migrations.RenameModel(
            old_name='HeadingBlock',
            new_name='HeadingBlockOne',
        ),
        migrations.AlterModelOptions(
            name='headingblockone',
            options={'verbose_name': 'Heading 1'},
        ),
    ]
