# Generated by Django 5.1.6 on 2025-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalchapter',
            name='name',
            field=models.CharField(choices=[('Food', 'Food'), ('People', 'People'), ('Language', 'Language'), ('Artforms', 'Artforms'), ('Stories', 'Stories'), ('Cultural Sites', 'Cultural Sites'), ('Architecture', 'Architecture'), ('Sports & Games', 'Sports & Games'), ('Festivals & Fairs', 'Festivals & Fairs'), ('Political History', 'Political History'), ('Markets', 'Markets'), ('Local Politics', 'Local Politics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='culturalchapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='culturalsection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturalsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='culturalsection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
