# Generated by Django 5.1.7 on 2025-06-08 19:12

import culture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='alt_text',
            field=models.CharField(help_text='Accessibility text for screen readers.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='caption',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(upload_to=culture.models.get_seo_image_path),
        ),
    ]
