# Generated by Django 5.2.3 on 2025-09-03 09:16

import culture.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartBlock',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('title', models.CharField(blank=True, help_text="Title of the chart e.g., 'Population Growth'", max_length=255, null=True)),
                ('chart_html_file', models.FileField(help_text='Upload on The PreGenrated  .html File for the Chart', upload_to=culture.models.get_culture_chart_path)),
            ],
            options={
                'verbose_name': 'Chart Block (HTML Upload)',
            },
            bases=('culture.contentblock',),
        ),
    ]
