# Generated by Django 5.1.7 on 2025-03-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_imageinfo_remove_tablecell_row_remove_tablerow_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_infos', to='culture.culturalsection'),
        ),
    ]
