# Generated by Django 5.1.7 on 2025-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_alter_imageblock_alt_text_alter_imageblock_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
