# Generated by Django 5.1.7 on 2025-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_headingblocktwo_rename_headingblock_headingblockone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalchapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
