# Generated by Django 5.1.7 on 2025-03-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_imageinfo_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='source',
        ),
    ]
