# Generated by Django 5.1.7 on 2025-03-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_remove_imageinfo_caption_remove_imageinfo_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_info',
        ),
    ]
