# Generated by Django 5.1.7 on 2025-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_alter_contentblock_order_alter_imageblock_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='alt_text',
            field=models.CharField(help_text='Accessibility text for screen readers.', max_length=4000),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='caption',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
