# Generated by Django 5.1.7 on 2025-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0005_alter_imageblock_alt_text_alter_imageblock_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='alt_text',
            field=models.CharField(help_text='Accessibility text for screen readers.', max_length=255),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
