# Generated by Django 5.1.7 on 2025-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0005_remove_image_image_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ImageInfo',
        ),
    ]
