# Generated by Django 5.1.7 on 2025-05-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_image_description_delete_imageinfo'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='culturalchapter',
            unique_together={('district',)},
        ),
        migrations.AlterField(
            model_name='culturalchapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
