# Generated by Django 5.1.7 on 2025-06-09 02:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_alter_contentblock_order_alter_imageblock_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='alt_text',
            field=models.CharField(help_text='Accessibility text for screen readers.', max_length=4000),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='caption',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='paragraphblock',
            name='content',
            field=tinymce.models.HTMLField(help_text='Formatted text, lists, and tables go here.'),
        ),
    ]
