# Generated by Django 5.1.7 on 2025-05-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0007_alter_culturalchapter_unique_together_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='culturalchapter',
            unique_together={('district', 'name')},
        ),
    ]
