# Generated by Django 5.1.7 on 2025-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0007_alter_contentblock_order_alter_imageblock_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphblock',
            name='content',
            field=models.TextField(help_text='Formatted text, lists, and tables go here.'),
        ),
    ]
