# Generated by Django 5.1.7 on 2025-06-09 06:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0008_alter_paragraphblock_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphblock',
            name='content',
            field=tinymce.models.HTMLField(help_text='Formatted text, lists, and tables go here.'),
        ),
    ]
