# Generated by Django 5.1.7 on 2025-05-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0008_alter_culturalchapter_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='section',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
