# Generated by Django 5.1.7 on 2025-06-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0009_alter_paragraphblock_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingBlockThree',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture.contentblock')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Heading 3',
            },
            bases=('culture.contentblock',),
        ),
    ]
