# Generated by Django 5.1.7 on 2025-06-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0010_headingblockthree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalchapter',
            name='name',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Artforms', 'Artforms'), ('Cultural Sites', 'Cultural Sites'), ('Festivals & Fairs', 'Festivals & Fairs'), ('Food', 'Food'), ('Language', 'Language'), ('Local Politics', 'Local Politics'), ('Markets', 'Markets'), ('Political History', 'Political History'), ('Sports & Games', 'Sports & Games'), ('Stories', 'Stories')], max_length=50),
        ),
    ]
