# Generated by Django 5.2.3 on 2025-06-24 16:59

import culture.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0011_alter_culturalchapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(upload_to=culture.models.get_seo_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Original Image'),
        ),
    ]
