# Generated by Django 5.2.3 on 2025-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0012_alter_imageblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceblock',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
