# Generated by Django 5.2.3 on 2025-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0013_alter_referenceblock_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceblock',
            name='text',
            field=models.TextField(),
        ),
    ]
