# Generated by Django 5.2.3 on 2025-06-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0014_alter_referenceblock_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceblock',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
